---
title: "Plex Music 2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard);library(tidyverse);library(httr);library(lubridate);library(treemapify);library(plotly)
token <- 'ABhPTJsJFC1CsCPKzzhb'

slug <- "http://192.168.1.99:32400/playlists/29522/items"

## Download playlist
play20raw <- content(httr::GET(slug, add_headers("X-Plex-Token" = token)), type = 'text') %>% 
    jsonlite::fromJSON() %>% 
    magrittr::extract2('MediaContainer') %>% 
    magrittr::extract2('Metadata')
play20 <- play20raw %>% select(
    artist    = grandparentTitle, 
    album       = parentTitle, 
    track       = title, 
    rating      = userRating,
    key         = ratingKey,
    artistKey   = grandparentRatingKey,
    albumKey    = parentRatingKey,
    trackNum       = index,
    discNum        = parentIndex
) %>% 
    as_tibble()
```

Row {data-height=100}
----

```{r, out.width = "100%", fig.height = 0.5}
progress <- play20 %>% 
  summarise(n1 = n(), n2 = sum(!is.na(rating))) %>% 
  transmute(perc = n2/n1, tot = 1-perc) %>% 
  gather() %>% rowwise() %>%  
  mutate(label = ifelse(test = key == 'perc', 
                        yes = str_c(round(100*value, 0), "%"), no = "")) %>% 
  ggplot(aes(x = 1, y = value, fill = rev(key), alpha = rev(key))) + 
  geom_col(position = 'fill', color = "#003EBB", size = 1) + 
  coord_flip() + 
  scale_fill_manual(values = (c("#C1D1F4", "#003EBB"))) + 
  scale_alpha_manual(values = c(0.5, 1)) + 
  geom_label(aes(label = label, y = 0.9), size = 3, fill = 'white', label.size = 0)  + 
  theme_void()+ 
  theme(legend.position = 'none', 
        plot.background = element_rect(fill = 'white', color = 'white'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())
# ggplotly(progress) %>% layout(height=80)
progress
```

Row
-----------------------------------------------------------------------

### All albums

```{r}
play20 %>% 
    add_count(artist, album) %>% 
    na.omit() %>% 
    group_by(artist, album, n) %>%  
    summarise(avRat = round(mean(rating)/2, 2), 
              n1 = n(), .groups = 'drop') %>% 
    arrange(desc(avRat)) %>% 
    unite(n1, n, col = 'n', sep = "/") %>% 
  mutate('#' = row_number()) %>% 
  relocate('#', .before = 'artist') %>% 
    knitr::kable()
```

<!-- Row -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### Top songs so far -->

<!-- ```{r} -->
<!-- play20 %>% -->
<!--     select(artist, album, track, rating) %>%  -->
<!--     filter(rating > 7) %>% knitr::kable() -->

<!-- ``` -->

Row
-----------------------------------------------------------------------

### Album Plays (Plex in blue)

```{r}
source('scripts/getLastfm.R')
tracks <- getLastfm(T)
tracks %>% filter(year(date) == 2020) %>% 
  count(artist, album, sort = TRUE) %>% 
  na.omit() %>% 
  mutate(plex = ifelse(str_to_lower(artist) %in% str_to_lower(play20$artist) &
                         str_to_lower(album) %in% str_to_lower(play20$album),
                       TRUE, FALSE)) %>% 
  mutate(rank = row_number()) %>%
  group_by(plex) %>% 
  mutate(z = max(rank)) %>% 
  ungroup() %>% 
  mutate(z = ifelse(min(z) < 25, 25, min(z))) %>% 
  filter(rank <= z) %>% 
  unite(col = 'name', artist, album, sep = " - ") %>% 
  mutate(name = forcats::fct_rev(forcats::fct_inorder(name))) %>% 
  ggplot(aes(x = name, y = n, fill = plex, group = plex)) + 
  geom_col() + 
  scale_fill_manual(values = c('white', "#003EBB")) +
  theme(legend.position = 'none') +
  xlab(NULL) + ylab(NULL) +
  coord_flip()

```

### Track Plays (Plex in blue)

```{r}
tracks %>% filter(date >= "2020-1-01") %>% 
  filter(str_detect(artist, 'Duggee', negate = TRUE),
         str_detect(artist, 'Night Garden', negate = TRUE),
         str_detect(artist, 'Dora The Explorer', negate = TRUE),
         str_detect(track, "Havin' a Bath", negate = TRUE),
         str_detect(track, "Bojack", negate = TRUE)) %>% 
  count(artist, track, sort = TRUE) %>% 
  slice_head(n = 50) %>% 
  na.omit() %>% 
  mutate(plex = ifelse(str_to_lower(artist) %in% str_to_lower(play20$artist) &
                         str_to_lower(track) %in% str_to_lower(play20$track),
                       TRUE, FALSE)) %>% 
  mutate(rank = row_number()) %>%
  group_by(plex) %>% 
  mutate(z = max(rank)) %>% 
  ungroup() %>% 
  mutate(z = min(z)) %>% 
  filter(rank <= z) %>% 
  unite(col = 'name', artist, track, sep = " - ") %>% 
  mutate(name = forcats::fct_rev(forcats::fct_inorder(name))) %>% 
  ggplot(aes(x = name, y = n, fill = plex, group = plex)) + 
  geom_col() + 
  scale_fill_manual(values = c('white', "#003EBB")) +
  theme(legend.position = 'none') +
  xlab(NULL) + ylab(NULL) +
  coord_flip()
```



<!-- ```{r} -->
<!-- colPal <- c('#FFFFFF', colorRampPalette(c("#C1D1F4", "#003EBB"))(5)) -->
<!-- play20 %>%  -->
<!--     mutate(rating = replace_na(rating, 0)) %>%  -->
<!--     mutate(rating = as.factor(rating/2)) %>%  -->
<!--     mutate(title = str_c(artist, album, sep = ' - '), -->
<!--            title = forcats::fct_rev(title)) %>%  -->
<!--     ggplot(aes(x = trackNum, y = title,  -->
<!--                fill = rating, group = rating)) + -->
<!--     geom_point(shape = 21, size = 5) + -->
<!-- scale_fill_manual("", values = colPal,  -->
<!--                       limits = c(0, 1, 2, 3, 4, 5), -->
<!--                       labels = c(0, 1, 2, 3, 4, 5)) +    xlab(NULL) + ylab(NULL) -->

<!-- ``` -->



Row
-----------------------------------------------------------------------

### Chart D

```{r}
play20 %>% 
    mutate(rating0 = replace_na(rating, 0)/2, 
           rating = rating/2) %>% 
    mutate(text = str_c(artist, " - ", track, "<br>", "Rating: ", rating0)) %>% 
    ggplot(aes(x = trackNum, y = rating0, group = album, color = album, text = text)) + 
    geom_point(alpha = 0.5) + 
    geom_smooth(se = FALSE, span = 3, aes(y = rating))
plotly::ggplotly(tooltip = 'text')

```

