---
title: "Plex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
    
---

```{r global, include = FALSE, cache = TRUE}
# Load data in global chunk so it's accessible
library(flexdashboard);library(tidyverse);library(httr)
library(lubridate);library(treemapify);library(plotly)
library(jsonlite);library(rdrop2);library(DT);library(treemapify)

getPlex <- function(refresh = FALSE) {
  
  if (refresh) {
    token <- 'ABhPTJsJFC1CsCPKzzhb'
    plexRaw <- content(GET("http://192.168.1.99:32400/library/sections/3/search?type=10", add_headers("X-Plex-Token" = token)), type = 'text') %>% 
      jsonlite::fromJSON() %>% 
      pluck('MediaContainer') %>% 
      pluck('Metadata')
    
    plex <- plexRaw %>% select(
      albumArtist    = grandparentTitle, 
      artist      = originalTitle, 
      album       = parentTitle, 
      track       = title, 
      rating      = userRating,
      key         = ratingKey,
      artistKey   = grandparentRatingKey,
      albumKey    = parentRatingKey,
      trackNum       = index,
      discNum        = parentIndex,
      year           = parentYear
    ) %>% 
      mutate(artist = ifelse(is.na(artist), albumArtist, artist)) %>% 
      as_tibble()
    
    write.csv(plex, file = here::here('tempData', 'plexDB.csv'), 
              row.names = FALSE, fileEncoding = "UTF-8")
    rdrop2::drop_upload(file = here::here('tempData', "plexDB.csv"), 
                        path = "R/lastfm")
    
  } else {
    
    plex <- rdrop2::drop_read_csv(file = "R/lastfm/plexDB.csv") %>% 
      as_tibble()
    
  }
  
  return(plex)
  
}

getLastfm <- function(refresh = TRUE) {
    library(tidyverse);library(rdrop2);library(here)
    
    rdrop2::drop_download("R/lastfm/tracks.csv",
                          local_path = "tracks.csv",
                          overwrite = T)

    localData <- readr::read_csv("tracks.csv", lazy = F) %>%
        mutate(date = lubridate::ymd_hms(date)) %>%
        filter(!is.na(date)) %>%
        as_tibble()
    
    if (refresh) {
        maxDate = max(localData$date)
        user <- Sys.getenv('LASTFM_USER')
        api <- Sys.getenv('LASTFM_APIKEY')
        
        responseDF <- tibble()
        pageNum <- 1
        
        # Keep getting data from lastfm until it's caught up with local data.
        while (min(responseDF$date) >= maxDate) {
            url <- paste0(
                "http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=",
                user,
                "&api_key=",
                api,
                "&format=json&limit=200&page=",
                pageNum
            )
            responseRaw <- url %>%
                httr::GET(.) %>%
                httr::content(., as = "text") %>%
                jsonlite::fromJSON(., simplifyDataFrame = T, flatten = T) %>%
                magrittr::extract2(c('recenttracks', 'track')) %>%
                select(
                    track = name,
                    artist = `artist.#text`,
                    album = `album.#text`,
                    date = `date.#text`
                ) %>%
                mutate(date = lubridate::dmy_hm(date)) %>%
                na.omit()
            responseDF <- bind_rows(responseDF, responseRaw) %>%
                arrange(desc(date))
            pageNum <- pageNum + 1
        }
        
        # Then filter response for new tracks, and add to localData
        localData <- bind_rows(filter(responseDF, date > maxDate),
                               localData)
        
        ## Write a local csv (ignored in git) and upload to Dropbox. 
        write.csv(localData, file = "tracks.csv", row.names = FALSE, fileEncoding = "UTF-8")
        rdrop2::drop_upload(file = "tracks.csv", path = "R/lastfm")
    }
    
    return(localData)
}

getSlugs <- function(text) {
    
    library(stringr)
    text1 <- text %>% 
        str_to_lower() %>% 
        str_remove_all(pattern = "[[:punct:]]") %>% 
        str_replace_all(pattern = "&", "and") %>% 
        str_replace_all(pattern = "\\s{2,}", replacement = " ") %>% 
        str_trim(side = 'both') %>% 
        str_remove_all(pattern = "\\s\\(.*") %>% 
        str_replace_all(pattern = " ", replacement = "-")
    
    return(text1)
    
}

removeEve <- function(lastfm) {
  lastfm <- lastfm %>% 
    filter(
      str_detect(artist, "Cocomelon", negate = T),
      str_detect(artist, "Super Simple", negate = T),
      str_detect(artist, "Duggee", negate = T),
      str_detect(artist, "Lullaby", negate = T),
      str_detect(artist, "Night Garden", negate = T),
      str_detect(track, 'Night Garden', negate = T),
      str_detect(artist, 'Toddler Tunes', negate = T),
      str_detect(artist, 'Pinkfong', negate = T)
    )
}

plex <- getPlex(F)
lastfm <- getLastfm(F) %>% removeEve()


```

Sidebar {.sidebar data-width=250}
======================

```{r}
shiny::radioButtons(inputId = "chooseYear", label = "Select year:",
            choiceValues = c("All", '1950', '1960', '1970', '1980', '1990', 
                        c(2000:max(plex %>% na.omit() %>% pull(year)))), 
            choiceNames = c("All time", 
                            plex %>%
              filter(year >= 1950, albumArtist != 'Various Artists') %>% 
              mutate(choiceLabel = ifelse(
                year > 1999, year, 10*floor(year/10)
              )) %>% 
              distinct(albumArtist, album, choiceLabel) %>% 
              count(choiceLabel) %>% 
              arrange(choiceLabel) %>% 
              mutate(n = str_c("(", n, ")")) %>% 
              unite(choiceLabel, n, col = 'choiceLabel', sep = " ") %>% 
              pull(choiceLabel)),
              selected = max(plex$year, na.rm = TRUE)
)

actionButton(inputId = "refreshPlex", label = "Refresh Plex", icon = icon('refresh'))

actionButton(inputId = "refreshLastfm", label = "Refresh Lastfm", icon = icon("refresh"))

rv <- reactiveValues(plex = plex,
                     lastfm = lastfm)

observeEvent(eventExpr = input$refreshPlex,
             handlerExpr = {
               showNotification("Updating Plex...")
               rv$plex <- getPlex(T)
               showNotification("Plex Updated!", type = 'message')
             })

observeEvent(eventExpr = input$refreshLastfm,
             handlerExpr = {
               showNotification("Updating Lastfm")
               rv$lastfm <- getLastfm(T) %>% removeEve()
               showNotification("Lastfm Updated!", type = 'message')
             })

observeEvent(eventExpr = input$chooseYear,
             handlerExpr = {
               ## Option 1: All time
               if (input$chooseYear == "All") {
                 rv$chooseYear <- 3000
                 rv$plexYear <- rv$plex
                 ## Option 2: 1950s - 1990s (decades)
               } else if (str_detect(input$chooseYear, "^1")) {
                 minYear <- as.numeric(input$chooseYear)
                 maxYear <- minYear + 9
                 rv$chooseYear <- minYear
                 rv$plexYear <- filter(rv$plex, year >= minYear, year <= maxYear)
                 ## Option 3: 2000 onwards (years)
               } else {
                 rv$chooseYear <- input$chooseYear
                 rv$plexYear <- filter(rv$plex, year == as.numeric(input$chooseYear))  
               }
               
             })
```

Dashboard
======================

Row {data-height=50}
----

### Rating Progress

```{r, out.width = "100%", fig.height = 0.5, eval = T}
renderPlot({
  progress <-  rv$plexYear %>% 
    summarise(n1 = n(), n2 = sum(!is.na(rating))) %>% 
    transmute(perc = n2/n1, tot = 1-perc) %>% 
    gather() %>% rowwise() %>%  
    mutate(label = ifelse(test = key == 'perc', 
                          yes = str_c(round(100*value, 0), "%"), no = "")) %>% 
    ggplot(aes(x = 1, y = value, fill = rev(key), alpha = rev(key))) + 
    geom_col(position = 'fill', color = "#003EBB", size = 1) + 
    coord_flip() + 
    scale_fill_manual(values = (c("#C1D1F4", "#003EBB"))) + 
    scale_alpha_manual(values = c(0.5, 1)) + 
    geom_label(aes(label = label, y = 0.9), size = 3, fill = 'white', label.size = 0, fontface = 2)  + 
    theme_void()+ 
    theme(legend.position = 'none', 
          plot.background = element_rect(fill = 'white', color = 'white'),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank())
  # ggplotly(progress) %>% layout(height=80)
  progress
})

```

Row table
-----------------------------------------------------------------------

### All albums

```{r}
shiny::checkboxInput(inputId = "onlyComplete", label = "Only include complete ratings", value = FALSE)
```

```{r, eval = T, out.width ="100%"}
DT::renderDataTable({
  data <- rv$plexYear %>% 
    filter(albumArtist != 'Various Artists') %>% 
    group_by(albumArtist, album) %>% 
    ## Allow for an album to be missing 3 tracks before max trackNum
    filter(n() >= max(trackNum) - 3) %>% 
    summarise(x = n(), y = sum(!is.na(rating)),
              avRat = round(mean(rating, na.rm = TRUE) / 2, 2),
              .groups = 'drop') %>% 
    filter(x > 2) %>% 
    unite(col = 'match', albumArtist, album, sep = "-", remove = FALSE) %>% 
    mutate(match = getSlugs(match)) %>% 
    left_join(., 
              rv$lastfm %>% 
                unite(col = 'match', artist, album, sep = "-", remove = TRUE) %>% 
                mutate(match = getSlugs(match)) %>% 
                count(match, sort = T, name = 'Plays'),
              by = 'match') %>% 
    select(-match) %>% 
    arrange(desc(avRat)) %>% 
    unite(y, x, col = 'n', sep = "/")
    
  if (input$onlyComplete) {
    data <- data %>% 
      separate(col = 'n', sep = "/", into = c('x', 'y'), remove = FALSE) %>% 
      filter(x == y) %>% 
      select(-x, -y)
  }
  DT::datatable(data, options = list(
    bPaginate = TRUE
  ))
})

```

Row table
-----------------------------------------------------------------------

### Top Songs

```{r, eval = T, out.width ="100%"}
DT::renderDataTable({
  data <- rv$plexYear %>% 
      select(artist, track, rating) %>% 
      filter(rating > 6) %>% 
    unite(col = 'match', artist, track, sep = "-", remove = FALSE) %>% 
    mutate(match = getSlugs(match)) %>% 
    left_join(., 
              rv$lastfm %>%
              # lastfm %>% 
                unite(col = 'match', artist, track, sep = "-", remove = TRUE) %>% 
                mutate(match = getSlugs(match)) %>% 
                count(match, sort = T, name = 'Plays'),
              by = 'match') %>% 
    select(-match) %>% 
    arrange(desc(rating), desc(Plays)) 
    
    DT::datatable(data, options = list(
        bPaginate = TRUE
        ))
})

```

Row {data-height=50}
-----------------------------------------------------------------------

### 

```{r}
shiny::checkboxInput(inputId = "onlyPlex", label = "Only include Plex", value = FALSE)
```

Row {}
-----------------------------------------------------------------------

### Top Album Plays (Plex in blue)

```{r, eval = T}
renderPlot({
  
  if (rv$chooseYear == 3000) {
    ## Copy pretty much same as below, with entire lastfm history and entire plex library
    print ("All time")
    albums <- full_join(
      rv$lastfm %>%
        unite(col = 'match', artist, album, sep = "-", remove = FALSE) %>% 
        mutate(match = getSlugs(match)) %>% 
        count(artist, album, match, sort = T),
      rv$plex %>% 
        unite(col = 'match', albumArtist, album, sep = "-", remove = TRUE) %>% 
        mutate(match = getSlugs(match), inPlex = 1) %>%
        distinct(match, inPlex),
      by = 'match'
    ) %>% 
      arrange(desc(n)) %>% 
      mutate(inPlex = replace_na(inPlex, 0)) %>% 
      mutate(inPlex = as.factor(inPlex),
             rank = row_number())
  } else if(rv$chooseYear >= 2006) {
    print("2006")
    # From 2006 onwards, take 25 most played albums from lastfm, see if they're in plex
    inPlex <- rv$plex %>% 
      unite(col = 'match', albumArtist, album, sep = " - ", remove = TRUE) %>% 
      mutate(match = getSlugs(match), inPlex = 1) %>% 
      distinct(match, inPlex)
    lastfmCount <- rv$lastfm %>% 
      filter(year(date) == as.numeric(input$chooseYear)) %>%
      unite(col = 'match', artist, album, sep = " - ", remove = FALSE) %>% 
      mutate(match = getSlugs(match)) %>% 
      count(artist, album, match, sort = T) 
    albums <- left_join(
      lastfmCount,
      inPlex,
      by = 'match'
    ) %>% 
      arrange(desc(n)) %>% 
      mutate(inPlex = replace_na(inPlex, 0)) %>% 
      mutate(inPlex = forcats::as_factor(inPlex),
             rank = row_number())
    
    } else {
      # Before 2006 just take plex albums from that year and arrange by playcount
      plexCount <- rv$plexYear %>% 
        unite(col = 'match', albumArtist, album, sep = " - ", remove = FALSE) %>% 
        mutate(match = getSlugs(match), inPlex = 1) %>% 
        distinct(artist = albumArtist, album, match, inPlex)
    lastfmCount <- rv$lastfm %>% 
      unite(col = 'match', artist, album, sep = " - ", remove = TRUE) %>% 
      mutate(match = getSlugs(match)) %>% 
      count(match, sort = T)
    albums <- left_join(
      plexCount,
      lastfmCount,
      by = 'match'
    ) %>% 
      arrange(desc(n)) %>% 
      mutate(inPlex = replace_na(inPlex, 0)) %>% 
      mutate(inPlex = forcats::as_factor(inPlex),
             rank = row_number())
        
    }
    
    albums %>% 
      purrr::when(
        input$onlyPlex ~ filter(., inPlex == 1),
        ~ .
      ) %>% 
      slice(1:25) %>% 
      unite(col = 'name', artist, album, sep = " - ") %>% 
      mutate(nchar = nchar(name)) %>% 
      mutate(name = ifelse(nchar > 47, str_c(str_sub(name, 0, 47), "..."), name)) %>% 
      mutate(name = forcats::fct_rev(forcats::fct_inorder(name))) %>% 
      ggplot(aes(x = name, y = n, fill = inPlex, group = inPlex)) + 
      geom_col(width = 0.7, color = "#003EBB") + 
      scale_fill_manual(values = c('white', "#809FDD"),
                        breaks = c(0, 1)) +
      theme(legend.position = 'none') +
      xlab(NULL) + ylab(NULL) +
      coord_flip()
})
```

### Track Plays (Plex in blue)

```{r, eval = T}
renderPlot({
  
  if (rv$chooseYear == 3000) {
    ## Copy pretty much same as below, with entire lastfm history and entire plex library
    print ("All time")
    tracks <- full_join(
      rv$lastfm %>%
        unite(col = 'match', artist, track, sep = "-", remove = FALSE) %>% 
        mutate(match = getSlugs(match)) %>% 
        count(artist, track, match, sort = T),
      rv$plex %>% 
        unite(col = 'match', artist, track, sep = "-", remove = TRUE) %>% 
        mutate(match = getSlugs(match), inPlex = 1) %>%
        distinct(match, inPlex),
      by = 'match'
    ) %>% 
      arrange(desc(n)) %>% 
      mutate(inPlex = replace_na(inPlex, 0)) %>% 
      mutate(inPlex = as.factor(inPlex),
             rank = row_number())
  } else if(rv$chooseYear >= 2006) {
    print("2006")
    # From 2006 onwards, take 25 most played tracks from lastfm, see if they're in plex
    inPlex <- rv$plex %>% 
      unite(col = 'match', artist, track, sep = " - ", remove = TRUE) %>% 
      mutate(match = getSlugs(match), inPlex = 1) %>% 
      distinct(match, inPlex)
    lastfmCount <- rv$lastfm %>% 
      filter(year(date) == as.numeric(input$chooseYear)) %>%
      unite(col = 'match', artist, track, sep = " - ", remove = FALSE) %>% 
      mutate(match = getSlugs(match)) %>% 
      count(artist, track, match, sort = T)
    tracks <- left_join(
      lastfmCount,
      inPlex,
      by = 'match'
    ) %>% 
      arrange(desc(n)) %>% 
      mutate(inPlex = replace_na(inPlex, 0)) %>% 
      mutate(inPlex = forcats::as_factor(inPlex),
             rank = row_number())
    
    } else {
      # Before 2006 just take plex albums from that year and arrange by playcount
      plexCount <- rv$plexYear %>% 
        unite(col = 'match', artist, track, sep = " - ", remove = FALSE) %>% 
        mutate(match = getSlugs(match), inPlex = 1) %>% 
        distinct(artist, track, match, inPlex)
    lastfmCount <- rv$lastfm %>% 
      unite(col = 'match', artist, track, sep = " - ", remove = TRUE) %>% 
      mutate(match = getSlugs(match)) %>% 
      count(match, sort = T)
    tracks <- left_join(
      plexCount,
      lastfmCount,
      by = 'match'
    ) %>% 
      arrange(desc(n)) %>% 
      mutate(inPlex = replace_na(inPlex, 0)) %>% 
      mutate(inPlex = forcats::as_factor(inPlex),
             rank = row_number())
        
    }
    
    tracks %>% 
      purrr::when(
        input$onlyPlex ~ filter(., inPlex == 1),
        ~ .
      ) %>% 
      slice(1:25) %>% 
      unite(col = 'name', artist, track, sep = " - ") %>% 
      mutate(nchar = nchar(name)) %>% 
      mutate(name = ifelse(nchar > 47, str_c(str_sub(name, 0, 47), "..."), name)) %>% 
      mutate(name = forcats::fct_rev(forcats::fct_inorder(name))) %>% 
      ggplot(aes(x = name, y = n, fill = inPlex, group = inPlex)) + 
      geom_col(width = 0.7, color = "#003EBB") + 
      scale_fill_manual(values = c('white', "#809FDD"),
                        breaks = c(0, 1)) +
      theme(legend.position = 'none') +
      xlab(NULL) + ylab(NULL) +
      coord_flip()
})
```



Row
-----------------------------------------------------------------------

### Ratings 1

```{r, eval = T}
renderPlot({
  colPal <- c('#FFFFFF', colorRampPalette(c("#C1D1F4", "#003EBB"))(5))
  
## Only really space for at most 50 albums, so just select 50 with most tracks?
rv$plexYear %>%
  filter(albumArtist != 'Various Artists') %>% 
  ## Too many albums with just one or two tracks, e.g. Al Green Greatest Hist
  ## Allow for max 3 missing tracks, so number of tracks in album has to be same as 
  ## highest track number minus 3?
  group_by(albumArtist, album) %>% 
  filter(n() >= max(trackNum) - 3) %>% 
  ungroup() %>% 
  mutate(album = ifelse(nchar(album) > 15, 
                        str_c(str_sub(album, 0, 13), "..."),
                        album)) %>%
  mutate(artist = ifelse(nchar(albumArtist) > 15, 
                         str_c(str_sub(albumArtist, 0, 13), "..."),
                         albumArtist)) %>%
  group_by(albumArtist, album) %>% 
  purrr::when(
    input$onlyComplete ~ filter(., !is.na(sum(rating))),
    ~ .
    ) %>%   
  ungroup() %>% 
  mutate(rating = replace_na(rating, 0)) %>%
  group_by(albumArtist, album) %>% 
  mutate(avRat = mean(rating), count = n()) %>% 
  group_by(albumArtist, album, avRat, count) %>% 
  nest() %>% 
  ungroup() %>% 
  arrange(desc(avRat)) %>% 
  filter(count > 2) %>% 
  slice(1:50) %>% 
  unnest() %>% 
  mutate(rating = as.factor(rating/2)) %>%
  mutate(title = str_c(artist, album, sep = ' - ')) %>% 
  arrange(title) %>% 
  mutate(title = forcats::fct_rev(title)) %>%
  ggplot(aes(x = trackNum, y = title,
             fill = rating, group = rating)) +
  geom_point(shape = 21, size = 5) +
  scale_fill_manual("", values = colPal,
                    limits = c(0, 1, 2, 3, 4, 5),
                    labels = c(0, 1, 2, 3, 4, 5)) +    xlab(NULL) + ylab(NULL)

})

```




### Ratings 2

```{r, eval = T}
renderPlot({
  colors <- c('#FFFFFF', '#6475C4', '#3B50B2')
  rv$plexYear %>% 
    group_by(albumArtist, album) %>% 
  filter(n() >= max(trackNum) - 3) %>% 
    purrr::when(
      input$onlyComplete ~ filter(., !is.na(sum(rating))),
      ~ .
    ) %>%   
    ungroup() %>% 
    mutate(rating = ifelse(rating == 0, NA, rating)) %>% 
    group_by(album) %>% 
    mutate(y = n(), count = n()) %>% 
    filter(count > 2) %>% 
    na.omit() %>% 
    mutate(x = n()) %>% 
    group_by(album, x, y) %>% summarise(avRat = mean(rating) / 2, .groups = 'drop') %>% 
    arrange(desc(avRat)) %>% 
    slice(1:25) %>% 
    arrange(avRat) %>% 
    mutate(album = str_c(album, "\n", "(", round(avRat, 1), ")")) %>% 
    mutate(album = forcats::fct_inorder(album)) %>% 
    mutate(compRat = (x/y)*avRat) %>% 
    select(-x, -y) %>% 
    gather(-album, key = series, value = Rating) %>% 
    ggplot(aes(x = album, y = Rating, group = series, fill = series)) +
    geom_col(position = 'identity', color = colors[3], size = 0.5, width = 0.7) +
    scale_fill_manual(values = c(colors[1], colors[2])) + 
    coord_flip() +
    labs(x = NULL, y = NULL) +
    theme(legend.position = 'none')
  
  
})


```

All albums
======================

Row {data-height=50}
-----------------------------------------------------------------------

```{r}
shiny::checkboxInput(inputId = "complete2", label = "Only complete ratings", value = FALSE)
```

Row {data-height=100}
-----------------------------------------------------------------------

### 

```{r}
shiny::textInput(inputId = 'filterText', label = 'Search', width = "100%")
```

Row {}
-----------------------------------------------------------------------

### 

```{r fig.height=96}

renderPlotly({
colors <- c('#FFFFFF', '#6475C4', '#3B50B2')

plotData <- rv$plexYear %>% 
  unite(albumArtist, album, col = 'filterText', sep = " ", remove = FALSE) %>% 
  mutate(filterText = getSlugs(filterText)) %>% 
  filter(str_detect(string = filterText, pattern = getSlugs(input$filterText))) %>% 
  select(-filterText) %>% 
  group_by(albumArtist, album) %>% 
  filter(n() >= max(trackNum) - 3) %>% 
  purrr::when(
    input$complete2 ~ filter(., !is.na(sum(rating))),
    ~ .
  ) %>%   
  ungroup() %>% 
  mutate(rating = ifelse(rating == 0, NA, rating)) %>% 
  group_by(album) %>% 
  mutate(y = n(), count = n()) %>% 
  filter(count > 2) %>% 
  na.omit() %>% 
  mutate(x = n()) %>% 
  group_by(albumArtist, album, x, y) %>% summarise(avRat = mean(rating) / 2, .groups = 'drop') %>% 
  # slice(1:25) %>% 
  arrange(avRat) %>% 
  mutate(album = str_c(album, " (", round(avRat, 2), ")")) %>% 
  mutate(album = forcats::fct_inorder(album)) %>% 
  mutate(compRat = (x/y)*avRat) %>% 
  select(-x, -y) %>% 
  gather(-album, -albumArtist, key = series, value = Rating)

plotly::plot_ly(plotData %>% filter(series == 'avRat'), 
                x = ~Rating, y = ~album, type = 'bar', orientation = 'h',
                text = ~str_c(albumArtist, ": ", album), hoverinfo = 'text',
                marker = list(color = colors[1], 
                              line = list(color = colors[2], width = 0.2))) %>% 
  add_trace(data = plotData %>% filter(series == 'compRat'),
            marker = list(color = colors[2]), hoverinfo = 'none') %>% 
  layout(xaxis= list(title = ""),
         yaxis = list(title = "",
                     tickfont = list(size = ifelse(
                       nrow(plotData) > 1000, 6, 12
                     )),
                     dtick = 1),
         showlegend = FALSE,
         barmode = 'overlay',
         margin = list(l = 4*max(nchar(as.character(plotData$album)))),
         height = ifelse(
           nrow(plotData) > 1000, 5000,
           ifelse(nrow(plotData) > 50, 
                         nrow(plotData)*10, 
                         ifelse(nrow(plotData) > 20, 
                                nrow(plotData) * 15, 250))))

  # ggplot(aes(x = album, y = Rating, group = series, fill = series)) +
  # geom_col(position = 'identity', color = colors[3], size = 0.5, width = 0.7) +
  # scale_fill_manual(values = c(colors[1], colors[2])) + 
  # coord_flip() +
  # labs(x = NULL, y = NULL) +
  # theme(legend.position = 'none')
})
```

